# Generated by Django 3.2.7 on 2021-09-25 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummyvalue', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('skills_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_finder.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rate', models.FloatField()),
                ('years_exp', models.IntegerField()),
                ('current_proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_finder.project')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_finder.skill')),
            ],
        ),
    ]
