# Generated by Django 3.2.7 on 2021-09-25 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team_finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='current_proj',
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_proj',
            field=models.ManyToManyField(to='team_finder.Project'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(to='team_finder.Skill'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills_req',
        ),
        migrations.AddField(
            model_name='project',
            name='skills_req',
            field=models.ManyToManyField(to='team_finder.Skill'),
        ),
    ]
