# Generated by Django 3.2.7 on 2021-09-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_finder', '0002_auto_20210925_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='dummyvalue',
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
