# Generated by Django 3.2.7 on 2021-09-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_finder', '0003_auto_20210925_1920'),
        ('team_finder', '0003_auto_20210925_2159'),
    ]

    operations = [
    ]
