# Generated by Django 3.2.7 on 2021-09-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_finder', '0005_auto_20210926_1210'),
        ('team_finder', '0005_auto_20210926_1449'),
    ]

    operations = [
    ]
